#include "Video.h"

#ifdef __cplusplus
	#define __STDC_CONSTANT_MACROS
	#ifdef _STDINT_H
		#undef _STDINT_H
	#endif
	#include <stdint.h>
#endif
#ifdef __cplusplus
extern "C" {
#include <libavformat/avformat.h>
#include <libavcodec/avcodec.h>
#include <libswscale/swscale.h>
}
#endif

#include <GL/gl.h>

Video::Video()
	: m_pFormatCtx(0), m_pCodecCtx(0), m_pCodec(0), m_pFrame(0), m_pFrameRGB(0),
	  m_pBuffer(0), m_nBufferSize(0), m_nVideoStream(-1), m_unCurrentFrameGLIndex(0)
{
}

Video::~Video()
{
	if (this->m_pBuffer != 0)
		av_free(this->m_pBuffer);

	if (this->m_pFrameRGB != 0)
		av_free(this->m_pFrameRGB);

	if (this->m_pFrame != 0)
		av_free(this->m_pFrame);

	if (this->m_pCodecCtx != 0)
		avcodec_close(this->m_pCodecCtx);

	if (this->m_pFormatCtx != 0)
		av_close_input_file(this->m_pFormatCtx);
}

bool Video::load(const char* filename)
{
    // Register all formats and codecs
    av_register_all();

    // Open video file
    if(av_open_input_file(&m_pFormatCtx, filename, NULL, 0, NULL)!=0)
        return false; // Couldn't open file

    // Retrieve stream information
    if(av_find_stream_info(m_pFormatCtx)<0)
        return false; // Couldn't find stream information

    // Dump information about file onto standard error
    dump_format(m_pFormatCtx, 0, filename, false);

    // Find the first video stream
    m_nVideoStream=-1;
    for(unsigned int i=0; i<m_pFormatCtx->nb_streams; i++)
    {
        if(m_pFormatCtx->streams[i]->codec->codec_type==CODEC_TYPE_VIDEO)
        {
            m_nVideoStream=i;
            break;
        }
    }
    if(m_nVideoStream==-1)
        return false; // Didn't find a video stream

    // Get a pointer to the codec context for the video stream
    m_pCodecCtx=m_pFormatCtx->streams[m_nVideoStream]->codec;

    // Find the decoder for the video stream
    m_pCodec=avcodec_find_decoder(m_pCodecCtx->codec_id);
    if(m_pCodec==NULL)
        return false; // Codec not found

    // Open codec
    if(avcodec_open(m_pCodecCtx, m_pCodec)<0)
        return false; // Could not open codec

    // Hack to correct wrong frame rates that seem to be generated by some codecs
    if(m_pCodecCtx->time_base.num>1000 && m_pCodecCtx->time_base.den==1)
		m_pCodecCtx->time_base.den=1000;

    // Allocate video frame
    m_pFrame=avcodec_alloc_frame();

    // Allocate an AVFrame structure
    m_pFrameRGB=avcodec_alloc_frame();
    if(m_pFrameRGB==NULL)
        return false;

    // Determine required buffer size and allocate buffer
    m_nBufferSize=avpicture_get_size(PIX_FMT_RGB24, m_pCodecCtx->width, m_pCodecCtx->height);

    m_pBuffer=(uint8_t*)malloc(m_nBufferSize);

    // Assign appropriate parts of buffer to image planes in pFrameRGB
    avpicture_fill((AVPicture *)m_pFrameRGB, m_pBuffer, PIX_FMT_RGB24, m_pCodecCtx->width, m_pCodecCtx->height);

    return true;
}

void Video::nextFrame()
{
	if (this->m_pFormatCtx != 0)
	{
		int frameFinished;
		AVPacket packet;
		while(av_read_frame(m_pFormatCtx, &packet)>=0)
		{
			// Is this a packet from the video stream?
			if(packet.stream_index==m_nVideoStream)
			{
				// Decode video frame
				avcodec_decode_video2(m_pCodecCtx, m_pFrame, &frameFinished, &packet);

				// Did we get a video frame?
				if(frameFinished)
				{
					static struct SwsContext *img_convert_ctx;

					// Convert the image into YUV format that SDL uses
					if(img_convert_ctx == NULL)
					{
						int w = m_pCodecCtx->width;
						int h = m_pCodecCtx->height;

						img_convert_ctx = sws_getContext(w, h,
						m_pCodecCtx->pix_fmt,
						w, h, PIX_FMT_RGB24, SWS_BICUBIC,
						NULL, NULL, NULL);
						if(img_convert_ctx == NULL)
						{
							fprintf(stderr, "Cannot initialize the conversion context!\n");
							exit(1);
						}
					}
					sws_scale(img_convert_ctx, m_pFrame->data, m_pFrame->linesize, 0, m_pCodecCtx->height, m_pFrameRGB->data, m_pFrameRGB->linesize);

					this->uploadFrame(m_pFrameRGB, m_pCodecCtx->width, m_pCodecCtx->height);
					break;
				}
			}

			// Free the packet that was allocated by av_read_frame
			av_free_packet(&packet);
		}
	}
}

void Video::uploadFrame(AVFrame* pFrame, int width, int height)
{
	char* buff = new char[width * height * 3];
	char* tmp = buff;

    // Write pixel data
    for(int y=0; y<height; y++)
    {
        //fwrite(pFrame->data[0]+y*pFrame->linesize[0], 1, width*3, pFile);
    	memcpy(tmp, pFrame->data[0]+y*pFrame->linesize[0], width*3);
    	tmp += width*3;
    }

	if (m_unCurrentFrameGLIndex != 0)
	{
		glDeleteTextures(1, &m_unCurrentFrameGLIndex);
	}
	glGenTextures(1, &m_unCurrentFrameGLIndex);
	glBindTexture(GL_TEXTURE_2D, m_unCurrentFrameGLIndex);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);

	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB,
		width, height, 0,
		GL_RGB, GL_UNSIGNED_BYTE,
		(GLvoid*)buff);
	delete []buff;
}

void Video::render()
{
	glColor3f(1, 1, 1);
	glEnable(GL_TEXTURE_2D);
	glBindTexture(GL_TEXTURE_2D, m_unCurrentFrameGLIndex);
	glBegin(GL_QUADS);
	glTexCoord2f(0, 1); glVertex2f(-0.8f, -0.8f);
	glTexCoord2f(0, 0); glVertex2f(-0.8f, 0.4f);
	glTexCoord2f(1, 0); glVertex2f(0.8f, 0.4f);
	glTexCoord2f(1, 1); glVertex2f(0.8f, -0.8f);
	glEnd();
	glDisable(GL_TEXTURE_2D);
}
