#include "Video.h"

#ifdef __cplusplus
#define __STDC_CONSTANT_MACROS
#ifdef _STDINT_H
#undef _STDINT_H
#endif
#include <stdint.h>
#endif
#ifdef __cplusplus
extern "C" {
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libswscale/swscale.h>
}
#endif

#include <glad/glad.h>

Video::Video()
    : m_pFormatCtx(0), m_pCodecCtx(0), m_pCodec(0), m_pFrame(0), m_pFrameRGB(0), m_pBuffer(0), m_nBufferSize(0), m_nVideoStream(-1), m_unCurrentFrameGLIndex(0)
{
}

Video::~Video()
{
    if (this->m_pBuffer != 0)
        av_free(this->m_pBuffer);

    if (this->m_pFrameRGB != 0)
        av_free(this->m_pFrameRGB);

    if (this->m_pFrame != 0)
        av_free(this->m_pFrame);

    if (this->m_pCodecCtx != 0)
        avcodec_close(this->m_pCodecCtx);

    if (this->m_pFormatCtx != 0)
        avformat_close_input(&this->m_pFormatCtx);
}

bool Video::load(const char *filename)
{
    // Register all formats and codecs
    av_register_all();

    // Open video file
    if (avformat_open_input(&m_pFormatCtx, filename, NULL, NULL) != 0)
        return false; // Couldn't open file

    // Retrieve stream information
    if (avformat_find_stream_info(m_pFormatCtx, NULL) < 0)
        return false; // Couldn't find stream information

    // Dump information about file onto standard error
    // dump_format(m_pFormatCtx, 0, filename, false);

    // Find the first video stream
    m_nVideoStream = -1;
    for (unsigned int i = 0; i < m_pFormatCtx->nb_streams; i++)
    {
        if (m_pFormatCtx->streams[i]->codec->codec_type == AVMEDIA_TYPE_VIDEO)
        {
            m_nVideoStream = i;
            break;
        }
    }
    if (m_nVideoStream == -1)
        return false; // Didn't find a video stream

    // Get a pointer to the codec context for the video stream
    m_pCodecCtx = m_pFormatCtx->streams[m_nVideoStream]->codec;

    // Find the decoder for the video stream
    m_pCodec = avcodec_find_decoder(m_pCodecCtx->codec_id);
    if (m_pCodec == NULL)
        return false; // Codec not found

    // Open codec
    if (avcodec_open2(m_pCodecCtx, m_pCodec, NULL) < 0)
        return false; // Could not open codec

    // Hack to correct wrong frame rates that seem to be generated by some codecs
    if (m_pCodecCtx->time_base.num > 1000 && m_pCodecCtx->time_base.den == 1)
        m_pCodecCtx->time_base.den = 1000;

    // Allocate video frame
    m_pFrame = av_frame_alloc();

    // Allocate an AVFrame structure
    m_pFrameRGB = av_frame_alloc();
    if (m_pFrameRGB == NULL)
        return false;

    // Determine required buffer size and allocate buffer
    m_nBufferSize =
        avpicture_get_size(AV_PIX_FMT_RGB24, m_pCodecCtx->width, m_pCodecCtx->height);

    m_pBuffer = (uint8_t *)malloc(m_nBufferSize);

    // Assign appropriate parts of buffer to image planes in pFrameRGB
    avpicture_fill((AVPicture *)m_pFrameRGB,
                   m_pBuffer,
                   AV_PIX_FMT_RGB24,
                   m_pCodecCtx->width,
                   m_pCodecCtx->height);

    m_videoWidth = m_pCodecCtx->width;
    m_videoHeight = m_pCodecCtx->height;

    return true;
}

void Video::nextFrame()
{
    if (this->m_pFormatCtx != 0)
    {
        int frameFinished;
        AVPacket packet;
        while (av_read_frame(m_pFormatCtx, &packet) >= 0)
        {
            // Is this a packet from the video stream?
            if (packet.stream_index == m_nVideoStream)
            {
                // Decode video frame
                avcodec_decode_video2(m_pCodecCtx, m_pFrame, &frameFinished, &packet);

                // Did we get a video frame?
                if (frameFinished)
                {
                    static struct SwsContext *img_convert_ctx;

                    // Convert the image into YUV format that SDL uses
                    if (img_convert_ctx == NULL)
                    {
                        int w = m_pCodecCtx->width;
                        int h = m_pCodecCtx->height;

                        img_convert_ctx = sws_getContext(w,
                                                         h,
                                                         m_pCodecCtx->pix_fmt,
                                                         w,
                                                         h,
                                                         AV_PIX_FMT_RGB24,
                                                         SWS_BICUBIC,
                                                         NULL,
                                                         NULL,
                                                         NULL);
                        if (img_convert_ctx == NULL)
                        {
                            fprintf(stderr, "Cannot initialize the conversion context!\n");
                            exit(1);
                        }
                    }
                    sws_scale(img_convert_ctx,
                              m_pFrame->data,
                              m_pFrame->linesize,
                              0,
                              m_pCodecCtx->height,
                              m_pFrameRGB->data,
                              m_pFrameRGB->linesize);

                    this->uploadFrame(
                        m_pFrameRGB, m_pCodecCtx->width, m_pCodecCtx->height);
                    break;
                }
            }

            // Free the packet that was allocated by av_read_frame
            av_free_packet(&packet);
        }
    }
}

void Video::uploadFrame(AVFrame *pFrame, int width, int height)
{
    char *buff = new char[width * height * 3];
    char *tmp = buff;

    // Write pixel data
    for (int y = 0; y < height; y++)
    {
        // fwrite(pFrame->data[0]+y*pFrame->linesize[0], 1, width*3, pFile);
        memcpy(tmp, pFrame->data[0] + y * pFrame->linesize[0], width * 3);
        tmp += width * 3;
    }

    if (m_unCurrentFrameGLIndex != 0)
    {
        glDeleteTextures(1, &m_unCurrentFrameGLIndex);
    }
    glGenTextures(1, &m_unCurrentFrameGLIndex);
    glBindTexture(GL_TEXTURE_2D, m_unCurrentFrameGLIndex);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);

    glTexImage2D(GL_TEXTURE_2D,
                 0,
                 GL_RGB,
                 width,
                 height,
                 0,
                 GL_RGB,
                 GL_UNSIGNED_BYTE,
                 (GLvoid *)buff);
    delete[] buff;
}

void Video::render(int w, int h)
{
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();

    glOrtho(0.0f, w, h, 0.0f, 0.0f, 1.0f);

    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();

    glPushMatrix();

    float scale = float(w) / float(m_videoWidth);
    float topMargin = ((float(m_videoHeight) * scale) - float(h)) / 2.0f;

    glColor3f(1, 1, 1);
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, m_unCurrentFrameGLIndex);

    glBegin(GL_QUADS);

    glTexCoord2f(0, 0);
    glVertex2f(0.0f, -topMargin);

    glTexCoord2f(0, 1);
    glVertex2f(0.0f, -topMargin + float(m_videoHeight) * scale);

    glTexCoord2f(1, 1);
    glVertex2f(float(m_videoWidth) * scale, -topMargin + float(m_videoHeight) * scale);

    glTexCoord2f(1, 0);
    glVertex2f(float(m_videoWidth) * scale, -topMargin);

    glEnd();
    glDisable(GL_TEXTURE_2D);

    glPopMatrix();
}
